[package]
name = "Ferric_Client"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.0", features = ["full"] }
uuid = { version = "1.3", features = ["v4"] }
sysinfo = "0.29.0"
hostname = "0.3"
base64 = "0.13"
serde_json = "1.0"
scrap = "0.5.0"
image = "0.24"
